language: python
python:
    - "2.7"
    - "3.5"
install:
    - sudo apt-get update
    - sudo apt-get install python-dev python3-dev
    - sudo apt-get install python-setuptools python3-setuptools
    - sudo apt-get install python-numpy
    - sudo apt-get install libtiff5-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk
    - sudo apt-get install libhdf5-serial-dev
    - sudo apt-get install python-scipy python-matplotlib python-nose
    - sudo easy_install pip
    - sudo pip install cython
    - pip install .
    - pip install pillow numpy h5py requests
    - pip install coveralls
script:
    - coverage run -m unittest discover
after_success: coveralls
