language: python
python:
    - "2.7"
    - "3.5"
install:
    - wget -O "/tmp/0000.tif" https://icme.hpc.msstate.edu/mediawiki/images/e/ee/SAND.TIF --no-check-certificate
    - sudo apt-get autoremove
    - sudo apt-get update
    - sudo apt-get install python-dev python3-dev
    - sudo apt-get install python-setuptools python3-setuptools
    - sudo apt-get install python-numpy
    - sudo apt-get install zlib1g-dev
    - sudo apt-get install libhdf5-serial-dev
    - sudo apt-get install python-scipy python-matplotlib python-nose
    - sudo easy_install pip
    - sudo pip install cython
    - pip install .
    - pip install pillow numpy h5py requests
    - pip install coveralls
    - pip install json-spec
    - pip install simplejson regex wget
script:
    - coverage run -m unittest discover
after_success: coveralls
